[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18.17.0"

# If you're using SvelteKit's built-in API routes
[functions]
  directory = "netlify/functions"

# For SPA fallback
[[_redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
